
---
- name: Build docker image & deploy on docker container
  gather_facts: true
  hosts: all
  tasks:
    - name: Build the image on local
      docker_image:
       name: nareshdt99/abctechnologies-1.0
       source: build
       build:
        path: .
       tag: latest
    - name: Log into DockerHub
      docker_login:
       username: nareshdt99
       password: 8142972264
       email: nareshdt99@gmail.com
    - name: Tag and push to docker hub on local
      docker_image:
       name: nareshdt99/abctechnologies-1.0
       repository: nareshdt99/abctechnologies-1.0
       push: yes
       source: local
    - name: Remove image
      ignore_errors: yes
      docker_image:
       state: absent
       name: nareshdt99/abctechnologies-1.0
       tag: latest
    - name: Log into DockerHub
      docker_login:
       username: nareshdt99
       password: 8142972264
       email: nareshdt99@gmail.com
    - name: Pull image from dockerhub repo
      docker_image:
       name: nareshdt99/abctechnologies-1.0
       source: pull
    #- name: Create the container
      #docker_container:
       #name: abctechnologies
       #image: nareshdt99/abctechnologies-1.0
       #ports:
        #- "80:8080"
    - name: kubernetes Deployment
      become: yes
      command: kubectl apply -f https://kubernetes-deploy.s3.ap-south-1.amazonaws.com/kube-deployment.yml
      ignore_errors: true
      args:
        chdir: $HOME
...
